//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JusTreatment
    {
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> PaidPrice { get; set; }
        public int ProcedureID { get; set; }
        public string PetName { get; set; }
        public int OwnerID { get; set; }
    
        public virtual JusPet JusPet { get; set; }
        public virtual JusProcedure JusProcedure { get; set; }
    }
}
